import React from "react";
import "./Meditation.css"
import AudioPlayer from "./AudioPlayer"

export default class Meditation extends React.Component {

  state = {
    timer: null
  }

  static timerInterval;

  handleSubmit = e => {
    e.preventDefault();
   const timer = e.target.meditateTime.value;
   if(timer!==""){
     this.setState({timer}, this.startCountdown());
   }
  }

  startCountdown = () => {
    this.timerInterval = setInterval(() => {
      if(this.state.timer > 0){
        this.setState({timer:this.state.timer-1});
      } else {
        clearInterval(this.timerInterval);
      }
    }, 1000);
  }

  /*

  {
    id: 1, // generated by db
    timer: 3600,
    meditationCompleted: 2020-09-02T14:37:48, // generated by db
    journalEntry: "lorem ipsum",
    journalSubmitted: 2020-09-02T15:37:00, // generated by db
  }

  */

  render(){
    return (
      <div className="App">
        <h1>Meditate</h1>
        {this.state.timer===null && (<form onSubmit={e=>this.handleSubmit(e)}>
          <select name="meditateTime">
            <option value="">Length of Meditation...</option>
            <option value="2">2 seconds</option>
            <option value="10">10 seconds</option>
            <option value="300">5 minutes</option>
            <option value="600">10 minutes</option>
            <option value="3600">1 hour</option>
          </select>
          <input type="submit" value="Start"/>
        </form>)}

       {this.state.timer > 0 && (
        <section>
          <h2>{`${parseInt(this.state.timer/60)}:${this.state.timer%60}`}</h2>
        </section>)}

        {this.state.timer===0 && (
          <>
            <form>
              <h2>Journal Entry</h2>
              <textarea defaultValue=""></textarea>
              <br />
              <input type="submit"/>
            </form>
            <button onClick={e=>this.setState({timer:null})}>Restart</button>
          </>
        )}

        <p>Assortment of classical music to listen to while meditating: </p>
        <AudioPlayer
          urls={[
            "https://www.mfiles.co.uk/mp3-downloads/beethoven-symphony6-1.mp3",
            "https://www.mfiles.co.uk/mp3-downloads/moonlight-movement1.mp3",
            "https://www.mfiles.co.uk/mp3-downloads/sugar-plum-fairy.mp3"
          ]}
        />
      </div>
    );
  }
}
